Add method hiding factor
Parean/semester-project pull request #3
Opened 2017-03-24 08:14 UTC by Parean

2017-03-24 20:06 UTC, alexander-bzikadze requested changes
Ассерты, ассерты и еще раз ассерты.
Хочется разделить src и inc папки, и примеры закинуть, например, в testExamples.
Не забываем про hpp
Еще неймспейс добавь, а котором мы говорили.
Пока semesterProject внешний неймспейс, потом переназовем

2017-03-24 20:06 UTC, alexander-bzikadze commented on application/src/CustomListener.cpp
> +#include "CustomListener.h"
Хочу .hpp
Идеология в том, чтобы было единообразно .cpp и .hpp.

2017-03-24 20:06 UTC, alexander-bzikadze commented on application/src/CustomListener.cpp
> +  //if class hasn't modifiers, modifier() will return empty vector
Я рекомендую ассерт все равно поставить - ассерт не бывает лишним, а смотрящим в код будет очевидно, что такого произойти не может.

Вопрос снят, думал почему-то, что указатель на вектор.

2017-03-24 20:06 UTC, alexander-bzikadze commented on application/src/CustomListener.cpp
> +  if (ctx->memberDeclaration()->methodDeclaration() || ctx->memberDeclaration()->constructorDeclaration())
Здесь тоже забыл, почему memberDeclaration() не возвращает nullptr - ассерт рекомендуется

2017-03-24 20:06 UTC, alexander-bzikadze commented on application/src/CustomListener.cpp
> +      auto classContext = classes.back();
auto здесь очень кстати, повезло, что все типы так хорошо совпадут.
back() возвращает & или const&, а [] принимает const&. Скорее всего, под ауто все отлично раскроется.

Тем не менее, я рекомендую писать auto const& явно.

Замечание снято, так как classes.back() возвращает указатель, его лучше копировать, а не хранить по ссылке, так что все хорошо.

Далее есть замечание про неопределенные поведение back(), так что нужен ассерт.

2017-03-24 20:06 UTC, alexander-bzikadze commented on application/src/CustomListener.cpp
> +      privateFieldsNumber[classContext] += 1;
++?

2017-03-24 20:06 UTC, alexander-bzikadze commented on application/src/CustomListener.cpp
> +  privateFieldsNumber[ctx] = 0;
[] возвращает ссылку и если надо, то конструирует объект. После этого ты ему присваиваешь 0 (насколько я понимаю, мапа именно так работает). Того лишнее присвоение. Безусловно, никак не сказывается на производительности, но мы учимся работать на плюсах хорошо.
Рекомендуется для вставки использовать предназначенный для того insert.
Вроде его можно через инициалайзер_лист, то есть в данном случае insert({ctx, 0});

2017-03-24 20:06 UTC, alexander-bzikadze commented on application/src/CustomListener.cpp
> +  assert(classes.back() == ctx);
На самом деле, здесь зарыт undefined_behaviour. classes может оказаться пустым и тогда стандарт не отвечает за то, что кинет back() ([http://en.cppreference.com/w/cpp/container/vector/back]). Нужен еще ассерт на непустоту classes.

2017-03-24 20:06 UTC, alexander-bzikadze commented on application/src/CustomListener.cpp
> +  for (auto m = methodsNumber.begin(), p = privateMethodsNumber.begin(); m != methodsNumber.end() && p != privateMethodsNumber.end(); m++, p++)
Длины methodsNumber и privateMethodNumber, конечно, должны быть одинаковыми, но ассерт не помешает.

2017-03-24 20:06 UTC, alexander-bzikadze commented on application/src/CustomListener.cpp
> +  return static_cast< float >(numOfPrivateMethods) / numOfMethods;
Статик каст радует, но тип примитивный, си_стайл каст вполне подошел бы.
Рекомендуется всегда юзать double.

2017-03-24 21:33 UTC, alexander-bzikadze commented on application/src/CustomListener.cpp
> +  //if class hasn't modifiers, modifier() will return empty vector
Вопрос снят, думал почему-то, что указатель на вектор.

2017-03-25 13:09 UTC, alexander-bzikadze commented on application/src/CustomListener.cpp
> +      auto classContext = classes.back();
Замечание снято, так как classes.back() возвращает указатель, его лучше копировать, а не хранить по ссылке, так что все хорошо.

2017-03-29 10:11 UTC, Parean commented on application/src/CustomListener.cpp
> +  privateFieldsNumber[ctx] = 0;
https://github.com/Parean/semester-project/pull/1#discussion_r107710293
Кхм, кхм

2017-03-29 10:18 UTC, Parean commented on application/src/CustomListener.cpp
> +  if (ctx->memberDeclaration()->methodDeclaration() || ctx->memberDeclaration()->constructorDeclaration())
Я не очень понял о чем ты
memberDeclaration точно не пустой, если modifier не пустой, так грамматика устроена
Если modifier пустой, сработает return в самом начале функции

2017-03-29 10:26 UTC, Parean commented on application/src/CustomListener.cpp
> +  return static_cast< float >(numOfPrivateMethods) / numOfMethods;
Не очень понял, считаешь ли ты что это нужно исправить или нет

2017-03-29 10:33 UTC, alexander-bzikadze commented on application/src/CustomListener.cpp
> +  privateFieldsNumber[ctx] = 0;
[Оператор []](http://www.cplusplus.com/reference/unordered_map/unordered_map/operator[]/)
Я почитал справку и пришел к выводу, что insert лучше.
Emplace не для этого - emplace для того, чтобы ты конструировал объект, то есть например передал указатель, когда у тебя ключи - shared_ptr.

2017-03-29 10:34 UTC, alexander-bzikadze commented on application/src/CustomListener.cpp
> +  return static_cast< float >(numOfPrivateMethods) / numOfMethods;
Я бы рекомендовал исправить, но это опционально.
Моя идеология, что приведение примитивных типов следует делать си-стайлом, чтобы не распиливать на 20 строк приведение.

2017-03-29 10:45 UTC, Parean commented on application/src/CustomListener.cpp
> +  return static_cast< float >(numOfPrivateMethods) / numOfMethods;
Окей

2017-03-29 11:13 UTC, Parean commented on application/src/CustomListener.cpp
> +  if (ctx->memberDeclaration()->methodDeclaration() || ctx->memberDeclaration()->constructorDeclaration())
@alexander-bzikadze

2017-03-30 18:05 UTC, Parean commented on application/src/CustomListener.cpp
> +  classesForTraversal.push(classes.back());
Мне кажется вот здесь криво написано, потому что я извлекаю объект из вектора лишний раз
Но у меня что-то не получилось написать вот так:
```
std::shared_ptr <semesterProject::ClassDescription> classDescription ( new semesterProject::ClassDescription(ctx->Identifier()->getText()));
classesForTraversal.push(classDescription);
```

Стек выдавал ошибку и говорил что не может сделать пуш. Подскажи пожалуйста как это лучше сделать

2017-04-01 21:02 UTC, alexander-bzikadze requested changes
Ох. Разберись все же с std::move)

2017-04-01 21:02 UTC, alexander-bzikadze commented on application/inc/classDescription.hpp
> +		void addAttribute(AccessModifier const &modifier, string const &newAttribute);
Поздравляю с двумя потенциальными копированиями одной строки.

2017-04-01 21:02 UTC, alexander-bzikadze commented on application/inc/classDescription.hpp
> +		int getNumberOfAttributes() const;
Количество size_t скорее.

2017-04-01 21:02 UTC, alexander-bzikadze commented on application/inc/classDescription.hpp
> +		vector<const string*> privateAttributes;
Если что, я пишу `string const*`, чтоб потом на меня не ругался.

2017-04-01 21:02 UTC, alexander-bzikadze commented on application/inc/customListener.hpp
> +			stack <shared_ptr <semesterProject::InterfaceDescription> > interfacesForTraversal;
Есть такая поговорка, я её от Смаля слышал. Подумайте, какой контейнер вам надо из stl. Вам нужен, например, стек. Подумайте дважды, трижды. И выберете вектор.

Все равно стек - обертка над вектором.

Опционально.

2017-04-01 21:02 UTC, alexander-bzikadze commented on application/inc/interfaceDescription.hpp
> +		void addMethod(MethodDescription *newMethod);
А нам надо метод менять? Может ему const вхреначить?

2017-04-01 21:02 UTC, alexander-bzikadze commented on application/inc/interfaceDescription.hpp
> +		int getNumberOfPrivateMethods() const;
Помечу здесь, чтобы ты не забыл, что здесь хорошо бы тоже size_t.

2017-04-01 21:02 UTC, alexander-bzikadze commented on application/inc/methodDescription.hpp
> +enum AccessModifier
Енамами стараются не пользоваться.
Используют Enum class.
+ Это явно не место для объявления енама, внеси его в публичную часть класса.

2017-04-01 21:02 UTC, alexander-bzikadze commented on application/inc/methodDescription.hpp
> +		MethodDescription(AccessModifier const &methodModifier, string const &methodName, string const &stringForHash);
Опять же про копирования.
Не надо думать, что я рак и пишу в конструкторе string без const&, это не просто так.
Ладно, думал донизу дойду, там скажу, но так и быть.
Логика такая - здесь ты обязан вызвать копирование, чтобы из const& скопировать себе. Когда ты передаешь по значению, ты не уверен, было ли еще копирование. Но у тебя строка и ты можешь сделать от неё std::move - тогда ты переданную по значению строку смувишь себе за О(1). 
Теперь в чем профит - вполне возможно, что тебе хотят передать строку, которая временный объект. И её захотят передать по std::move, чтобы лишний раз не копировать. Но бац, бац, бац, а сигнатуры такой у тебя нет. И  в результате ты вынуждаешь копировать строку лишний раз.

Здесь может и не критично, но тем не менее, пора изучать новые фишки.

2017-04-01 21:02 UTC, alexander-bzikadze commented on application/src/classDescription.cpp
> +	attributes.push_back(newAttribute);
Вот место, где у тебя копирование происходит. Замест этого рекомендуется принять по значению, а в вектор запихнуть std::move(newAttribute).

2017-04-01 21:02 UTC, alexander-bzikadze commented on application/src/classDescription.cpp
> +	return attributes.size();
Я был прав про size_t. Нафиг нам конвертация из size_t в int? Надо точно менять на size_t.

2017-04-01 21:02 UTC, alexander-bzikadze commented on application/inc/customListener.hpp
> +			double getAHF() const;
Логически классы надо разделить: этот класс - слушатель, ему пофиг на метрики, его задача собирать данные; задача же другого класса - получить извне данные и выдать метрику. Понятно, что это несильно критично, но, наверное, хотелось бы вынести.

2017-04-01 21:02 UTC, alexander-bzikadze commented on application/src/methodDescription.cpp
> +	name(move(methodName))
![8u78da](https://cloud.githubusercontent.com/assets/15484066/24582376/63d939d4-1737-11e7-87dc-29eaef12f713.jpg)

2017-04-01 21:13 UTC, Parean commented on application/src/classDescription.cpp
> +	return attributes.size();
Да, прости
Я просто про size_t узнал буквально пару дней назад и по привычке продолжаю int писать

2017-04-01 21:14 UTC, Parean commented on application/src/methodDescription.cpp
> +	name(move(methodName))
Я понял, понял
Я почитаю про move, просто нам про него не рассказывали, а тут он только потому что я копирнул конструктор из твоего класса, потому что лень было писать с нуля и move остался
Мем смешной, мне понравился

2017-04-01 21:15 UTC, Parean commented on application/inc/classDescription.hpp
> +		vector<const string*> privateAttributes;
string const* и const string* это же разные вещи?

2017-04-01 21:18 UTC, Parean commented on application/inc/customListener.hpp
> +			double getAHF() const;
Да, это разумно
Он будет для всех метрик? Предложи название пожалуйста, чтобы потом не морочиться с исправлением

2017-04-01 21:19 UTC, Parean commented on application/inc/customListener.hpp
> +			stack <shared_ptr <semesterProject::InterfaceDescription> > interfacesForTraversal;
Ну вот тут я хз
Мне кажется стек семантически понятнее в данном случае

2017-04-01 21:20 UTC, alexander-bzikadze commented on application/inc/classDescription.hpp
> +		vector<const string*> privateAttributes;
Нет, одинаковые.
Все указатель на const string.
Чтобы сделать const указатель надо string *const

2017-04-01 21:21 UTC, alexander-bzikadze commented on application/inc/customListener.hpp
> +			double getAHF() const;
Тебе надо логически выделить связанные метрики, например эти две в HidingFactor просто запихнуть.

2017-04-01 21:22 UTC, Parean commented on application/inc/methodDescription.hpp
> +enum AccessModifier
Про Enum class я ничего не слышал и погуглю, всю жизнь писал так
А по поводу объявления, я хотел у тебя спросить про это, но решил отложить вопрос до текущего момента
Куда его лучше воткнуть?
Разве этот enum является логически частью метода? Модификаторы ведь для полей тоже есть
И этот enum используется в классе интерфейса например да и в listener тоже
Я хз куда его идиологически правильнее впихнуть

2017-04-01 21:22 UTC, alexander-bzikadze commented on application/inc/customListener.hpp
> +			stack <shared_ptr <semesterProject::InterfaceDescription> > interfacesForTraversal;
Понятнее, но вектор всем понятен.
Тут еще дело в том, что например я, увидев метод push(), полез в справку вектора искать метод push(). Потом вспомнил про стек, так что опционально, но рекомендуется.
Все используют для всех целей вектор.

2017-04-01 21:24 UTC, alexander-bzikadze commented on application/inc/methodDescription.hpp
> +enum AccessModifier
Хм, разумно
Можно тогда просто запихнуть в неймспейс, не кидая в конкретный класс.
Не знаю, может хорошо бы отдельный файлик под него.

2017-04-01 21:28 UTC, Parean commented on application/inc/methodDescription.hpp
> +		MethodDescription(AccessModifier const &methodModifier, string const &methodName, string const &stringForHash);
Я почитаю про move, обещаю, но то что ты написал мне непонятно, это нужно вживую обсуждать, я слишком тупой

2017-04-01 21:31 UTC, alexander-bzikadze commented on application/inc/methodDescription.hpp
> +		MethodDescription(AccessModifier const &methodModifier, string const &methodName, string const &stringForHash);
Значит, ты думаешь, что я Рак.
Понятно.

2017-04-01 21:36 UTC, Parean commented on application/inc/classDescription.hpp
> +		vector<const string*> privateAttributes;
А имеет смысл вообще вот так написать?
```
vector<const string> attributes;
vector<string const* const> privateAttributes
```;

2017-04-01 21:45 UTC, Parean commented on application/inc/customListener.hpp
> +			double getAHF() const;
Я не уверен что есть смысл плодить классы для метрик, их будет много и смысла в этом никакого
Можно сделать просто один класс отдельный типо MetricsCalculator, у которого весь мнешний код будет просить метрики и все лисенеры инициализировать им

2017-04-01 21:47 UTC, alexander-bzikadze commented on application/inc/classDescription.hpp
> +		vector<const string*> privateAttributes;
Страдать впихиванием const везде и всюду не следует. Одно дело у тебя большой объект, а другое указатель. Нет, ругать тебя никто не станет, но читабельность ухудшает, а смысла мало. Конст строке не дает фигни в неё записать, а конст указателю? Особого смысла в этом нет

2017-04-01 21:50 UTC, alexander-bzikadze commented on application/inc/customListener.hpp
> +			double getAHF() const;
Хм, это походе на god object. Лучше не так. Будет один класс - банк данных. И несколько функций, вынимающих из него данные и выдающих их.

2017-04-01 22:13 UTC, Parean commented on application/inc/customListener.hpp
> +			double getAHF() const;
А как ты себе это представляешь? Чтобы взять из него данные, их нужно туда сначала положить
А чтобы их положить их нужно выдернуть из лисенеров, то есть получается, что лисенеры будут все обрабатывать как и сейчас, у них будут методы получения метрик, как и сейчас, только при этом будет еще один лишний класс, который вообще ничего нового не добавляет
Я же имел ввиду, что мы инициализируем объектом лисенеры и вместого того, чтобы вектора с классами, интерфейсами, и все подобным хранить в лисенерах, сложим их все в метод калькулятор и напишем ему разные сэтеры, чтобы складывать туда данные пока идет обход
Когда обход завершится лисенер становится уже не нужен и вся информация лежит в этом классе
Я не знаю почему это похоже по-твоему на god object по-моему наоборот адекватное разделение обязанностей

2017-04-02 07:57 UTC, alexander-bzikadze commented on application/inc/interfaceDescription.hpp
> +		InterfaceDescription& operator=(InterfaceDescription&&) = delete;
Здесь где-то зарыт виртуальный деструктор, мне казалось, что я успел его добавить.
Во всяком случае в моем пуллреквесте висит надпись, что его надо добавить.

2017-04-02 09:48 UTC, alexander-bzikadze commented on application/src/methodDescription.cpp
> +	name(move(methodName))
Неправильный порядок инициализации, странно что тебе ворнинг не кидает.
Вроде в компиляторах реализовано так, что это неважно, но по стандарту должно быть в том же порядке, как и в объявлении класса.

2017-04-02 09:48 UTC, alexander-bzikadze commented on application/src/methodDescription.cpp
> +	name(move(methodName))
Неправильный порядок инициализации, странно что тебе ворнинг не кидает.
Вроде в компиляторах реализовано так, что это неважно, но по стандарту должно быть в том же порядке, как и в объявлении класса.

2017-04-02 16:31 UTC, alexander-bzikadze approved these changes
Про виртуальные деструкторы замечание важное.
И юзинги нафиг убрать.
Так все хорошо, как поправишь, можешь заливать.
Напишу аппрув, чтобы потом ты не заставлял меня снова смотреть.

2017-04-02 16:31 UTC, alexander-bzikadze commented on application/inc/customListener.hpp
> +using namespace antlr4;
Ну не пиши ты юзинги в hpp, засоряет это пространство имен тех, кто наш hpp подгружает. Все using в cpp

2017-04-02 16:31 UTC, alexander-bzikadze commented on application/inc/methodDescription.hpp
> +		virtual ~MethodDescription() = default;
Нафиг убрать, кто будет от этой фигни наследоваться

2017-04-02 16:31 UTC, alexander-bzikadze commented on application/src/customListener.cpp
> +	return AccessModifier::PROTECTED;
По умолчанию в джаве протектед?
В любом случае стоит добавить проверку на protected, мне кажется.

2017-04-02 16:34 UTC, alexander-bzikadze commented
А теперь про калькулятор. Я считаю, что он должен стоять отдельно от других метрик. То есть рекомендовалось бы его переназвать во что-то другое, связанное именно с MHF и AHF. Пользователь вряд ли захочет, чтобы тул начал строить даг наследования, если ему нужно MHF, так что я рекомендую его переназвать и использовать отдельно.

Да, и еще кастом листенер это ужас, почему он до сих пор не стал HidingFactorListener?)

2017-04-02 16:46 UTC, alexander-bzikadze commented
Я придумал.
Я себе тоже сделаю класс treeMetricsCalculator. Но они будут в details, а внешние будут функции, которые уже их обрабатывают. Как-то так.

2017-04-02 16:48 UTC, Parean commented on application/inc/customListener.hpp
> +using namespace antlr4;
Блин, прости, я это пропустил
Он вообще нафиг не нужен всё и без него скомпилируется

2017-04-02 16:49 UTC, Parean commented on application/src/customListener.cpp
> +	return AccessModifier::PROTECTED;
Да, протектед

2017-04-02 17:10 UTC, merged