Added inheritance tree (dag). No metrics done yet. Request review.
Parean/semester-project pull request #4
Opened 2017-03-28 21:44 UTC by alexander-bzikadze

I'm thinking of lambda-template dfs to cover all possible needs. Planning.

2017-03-29 10:48 UTC, alexander-bzikadze commented on application/inc/interfaceDescription.hpp
> +	class InterfaceDescription
Надо добавить вирт деструктор конечно.

2017-03-29 17:42 UTC, Parean reviewed
Не хватает файла interfaceDescription.cpp

2017-03-29 17:42 UTC, Parean commented on application/src/currentlyBuildingTree.cpp
> +	nodeByName[nodes.back()->getInterface()->getName()] = nodes.back().get();
А так можно писать? back возвращает умный указатель, к нему разве можно применять getInterface?

2017-03-29 17:42 UTC, Parean commented on application/inc/currentlyBuildingTree.hpp
> +		using DoubleIterator = std::pair<std::vector<std::shared_ptr<semesterProject::Node>>::const_iterator, std::vector<std::vector<std::string>>::const_iterator>;
Я бы написал сюда комментарий, в котором словами написано зачем это нужно, потому что воспринимается эта строчка очень тяжело
Или хотя бы скобочки пробелами отделил и разбил на две строки вот так:
```
using DoubleIterator = std::pair <std::vector <std::shared_ptr <semesterProject::Node> >::const_iterator, 
                                  std::vector <std::vector <std::string> >::const_iterator>;
```

2017-03-29 17:44 UTC, alexander-bzikadze commented on application/src/currentlyBuildingTree.cpp
> +	nodeByName[nodes.back()->getInterface()->getName()] = nodes.back().get();
Конечно
У shared_ptr специально определен для того оператор ->

2017-03-29 17:44 UTC, alexander-bzikadze commented on application/inc/currentlyBuildingTree.hpp
> +		using DoubleIterator = std::pair<std::vector<std::shared_ptr<semesterProject::Node>>::const_iterator, std::vector<std::vector<std::string>>::const_iterator>;
Оке, логично.

2017-03-29 17:55 UTC, Parean commented on application/src/inheritanceTreeConstructorListener.cpp
> +			assert(x->classOrInterfaceType());
Исходя из грамматики у x так же может быть потомок primitiveType
Если он встретится, ассерт сработает и грохнет корректный файл
Здесь нужно не его, а обычный if + continue
Второй ассерт вроде правильный, но вообще, он вероятнее всего никогда не сработает, потому что пустоту идентификатора еще перед ним словит парсер и все грохнется

2017-03-29 17:55 UTC, Parean commented on application/src/inheritanceTreeConstructorListener.cpp
> +		assert(ctx->typeType()->classOrInterfaceType());
Здесь аналогично вышенаписанному

2017-03-29 17:55 UTC, Parean commented on application/src/inheritanceTreeConstructorListener.cpp
> +			assert(x->classOrInterfaceType());
И тут тоже

2017-03-29 17:56 UTC, Parean commented on application/src/currentlyBuildingTree.cpp
> +	nodeByName[nodes.back()->getInterface()->getName()] = nodes.back().get();
Окей, вопрос снимается

2017-03-29 17:57 UTC, alexander-bzikadze commented on application/src/inheritanceTreeConstructorListener.cpp
> +			assert(x->classOrInterfaceType());
Можно наследоваться от примитивных типов?

2017-03-29 17:58 UTC, Parean commented on application/src/inheritanceTreeConstructorListener.cpp
> +			assert(x->classOrInterfaceType());
Что?
Я не понял к чему этот вопрос

2017-03-29 18:00 UTC, Parean commented on application/src/inheritanceTreeConstructorListener.cpp
> +			assert(x->classOrInterfaceType());
typeType
    :   classOrInterfaceType ('[' ']')*
    |   primitiveType ('[' ']')*
    ;

classOrInterfaceType
    :   Identifier typeArguments? ('.' Identifier typeArguments? )*
    ;

primitiveType
    :   'boolean'
    |   'char'
    |   'byte'
    |   'short'
    |   'int'
    |   'long'
    |   'float'
    |   'double'
    ;
Вот кусок из грамматики, срабатывает или первое или второе
Если в тексте второе, функция вместо первого вернет nulptr и программа упадет, хотя грамматика распознается корректно

2017-03-29 18:00 UTC, alexander-bzikadze commented on application/src/inheritanceTreeConstructorListener.cpp
> +			assert(x->classOrInterfaceType());
Если в джаве нельзя наследоваться от примитивных типов, то в дереве не может быть потомок primitiveType. Надо узнать, можно ли в джаве наследоваться от примитивных типов. В плюсах нельзя.

2017-03-29 18:07 UTC, alexander-bzikadze commented on application/src/inheritanceTreeConstructorListener.cpp
> +			assert(x->classOrInterfaceType());
Я говорю, что такое не должно происходить, на мой взгляд, с точки зрения синтаксиса самой Джавы.
Так что этот вопрос пока откладывается.

2017-03-29 18:11 UTC, Parean commented on application/src/inheritanceTreeConstructorListener.cpp
> +			assert(x->classOrInterfaceType());
Я не знаю можно ли, но грамматика такое разбирает

2017-03-29 18:14 UTC, Parean commented
Окей, нужно спросить кого-нибудь 


---- Alexander Bzikadze wrote ----

> @alexander-bzikadze commented on this pull request.
> 
> In application/src/inheritanceTreeConstructorListener.cpp:
> 
> > +	{} + +void semesterProject::inheritanceTreeConstructorListener::enterInterfaceDeclaration(JavaParser::InterfaceDeclarationContext *ctx) +{ +	// Interface should contain a name. Otherwise it's a bag. +	assert(ctx->Identifier()); +	assert(!ctx->Identifier()->getText().empty()); +	const string inheritorName(ctx->Identifier()->getText()); +	vector<string> parentNames; + +	// Node is scaned for parent-interfaces and then a new mask for a future node is added to the future tree. +	if (ctx->typeList()) +	{ +		for (auto x : ctx->typeList()->typeType()) +		{ +			assert(x->classOrInterfaceType()); 
> 
> Я говорю, что такое не должно происходить, на мой взгляд, с точки зрения синтаксиса самой Джавы.
> Так что этот вопрос пока откладывается.
> 
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub, or mute the thread.

2017-03-29 18:15 UTC, Parean commented on application/src/inheritanceTreeConstructorListener.cpp
> +			assert(x->classOrInterfaceType());
Хорошо, спросим потом кого-нибудь

2017-03-29 18:46 UTC, alexander-bzikadze commented on application/src/inheritanceTreeConstructorListener.cpp
> +			assert(x->classOrInterfaceType());
![image](https://cloud.githubusercontent.com/assets/15484066/24470875/104315bc-14c9-11e7-8674-f86885ca4b0a.png)
![image](https://cloud.githubusercontent.com/assets/15484066/24470895/1eaa5f34-14c9-11e7-904f-426a80004021.png)
Вроде не должно происходить, потом еще у Тимофея предлагаю уточнить. Нагуглить за пару секунд не смог, но судя по этому это делать нельзя и народ этим вопросом не задается.

2017-04-01 21:51 UTC, alexander-bzikadze commented
Что-то я забыл пометить просьбу о ревью.

2017-04-02 15:17 UTC, Parean commented on application/inc/currentlyBuildingTree.hpp
> +	class CurrentlyBuildingTree
Нужен doxygen комментарий с кратким описанием для чего этот класс

2017-04-02 15:17 UTC, Parean commented on application/inc/inheritanceTree.hpp
> +	/// Class that represents the inheritance tree (dag actially).
@brief или \brief
Я предлагаю через @ потому что  выглядит лучше
https://www.stack.nl/~dimitri/doxygen/manual/commands.html#cmdbrief

2017-04-02 15:17 UTC, Parean commented on application/inc/inheritanceTree.hpp
> +		/// Takes two vectors and sets them as roots - interfaces, that have no parents - and nodes - all contained nodes.
Я когда первый раз читал, не понял что это тире и секунд двадцать вникал
Лучше вместо them написать первый устанавливает как корни, а второй как ноды
Ну и дефисы на тире поменять

2017-04-02 15:17 UTC, Parean commented on application/inc/inheritanceTree.hpp
> +		/// Returns reference to roots.
Ну вот это явный пример комментария, который не несет смысловой нагрузки

2017-04-02 15:17 UTC, Parean commented on application/inc/interfaceDescription.hpp
> +		InterfaceDescription(std::string interfaceName);
Тут тоже комментарии лишние, но я их убирал в своей ветке вроде бы

2017-04-02 15:17 UTC, Parean commented on application/inc/interfaceDescription.hpp
> +		std::string interfaceName;
Тут должно быть const?

2017-04-02 15:17 UTC, Parean commented on application/inc/inheritanceTreeConstructorListener.hpp
> +	/// Listener of the Antlr4 tree that construst inherintence tree.
@brief

2017-04-02 15:17 UTC, Parean commented on application/inc/node.hpp
> +	class Node
Я дальше уже не буду писать, просто пройдись по комментариям и добавь команды doxygen
brief нужен для того, чтобы в итоговой документации этот комментарий был кратким описанием класса

2017-04-02 15:17 UTC, Parean commented on application/inc/node.hpp
> +		/// Add inheritor to the contained interface.
Тоже наверное не буду писать возле каждого, но все комментарии лишены смысловой нагрузки

2017-04-02 15:17 UTC, Parean commented on application/inc/node.hpp
> +		/// Add inheritor to the contained interface.
Пройдись в общем по всей ветке и убери их

2017-04-02 15:17 UTC, Parean commented on application/src/inheritanceTreeConstructorListener.cpp
> +	assert(ctx->Identifier());
Я в своем коде такие асерты не писал 
Мне кажется в них нету смысла, потому что идентификатор в грамматике разбирает только такие идентификаторы, которые состоят хотя бы из одной буквы, пустой идентификатор сразу грохнется парсером и у нас даже дерева нормального не будет, мы не сможем по нему ходить

2017-04-02 15:57 UTC, Parean commented on application/inc/inheritanceTreeConstructorListener.hpp
> +		inheritanceTreeConstructorListener(CurrentlyBuildingTree& currentlyBuildingTree);
Я не знаю насколько это принципиально, но можно методы enter внести в приватную часть, просто потому что снаружи они не должны дергаться

2017-04-02 16:20 UTC, alexander-bzikadze commented on application/inc/inheritanceTree.hpp
> +	/// Class that represents the inheritance tree (dag actially).
Эх, это две клавиши нажимать, ну ладно. Мне особо все равно.

2017-04-02 16:21 UTC, alexander-bzikadze commented on application/src/inheritanceTreeConstructorListener.cpp
> +	assert(ctx->Identifier());
Ассерты лишними не бывают, я уж убирать их не буду.

2017-04-02 16:23 UTC, alexander-bzikadze commented on application/inc/inheritanceTreeConstructorListener.hpp
> +		inheritanceTreeConstructorListener(CurrentlyBuildingTree& currentlyBuildingTree);
Так они вроде паблик в исходном классе-родителе?

2017-04-02 16:29 UTC, Parean commented
А если их перенести в приват, они же извне недоступны будут? Я перенес у меня все скомпилировалось, правда я честно скажу, не пробовал вызвать методы
Но мне кажется они должны запретиться

2017-04-02 17:18 UTC, alexander-bzikadze commented on application/inc/inheritanceTreeConstructorListener.hpp
> +		inheritanceTreeConstructorListener(CurrentlyBuildingTree& currentlyBuildingTree);
Ну раз работает, тоже попытаюсь перенести.

2017-04-13 15:13 UTC, Parean requested changes
Я сразу говорю, что логику твоего кода я не смотрел, потому что для меня он слишком непонятный
Я написал только по поводу оформления и тех мест, которые понять был способен
Хочу чтобы ты написал по поводу того, стоит ли писать инклуды явно везде и по поводу auto const& и auto

2017-04-13 15:13 UTC, Parean commented on application/inc/classDescription.hpp
> -#include "accessModifier.hpp"
А зачем ты этот инклуд убрал? Здесь же используется в коде модификатор

2017-04-13 15:13 UTC, Parean commented on application/inc/classDescription.hpp
> +	std::vector<std::string> attributes;
Наверное надо сделать атрибуты константными

2017-04-13 15:13 UTC, Parean commented on application/inc/currentlyBuildingTree.hpp
> +	/// Adds new interface and its parents to masks.
Что такое маска? Это термин которого я не знаю?

2017-04-13 15:13 UTC, Parean commented on application/inc/currentlyBuildingTree.hpp
> +	/// With the help of masks builds a real tree. Continueing use of the object
Можно исправить  Continueing, но можно и забить

2017-04-13 15:13 UTC, Parean commented on application/inc/currentlyBuildingTree.hpp
> +	std::vector<std::shared_ptr<Node>> nodes;
Вот здесь тоже может константные ноды?
Я не знаю насколько обоснованно это, но ты вроде сам говорил писать const везде где только можно

2017-04-13 15:13 UTC, Parean commented on application/inc/graphSearsFunctions.hpp
> +namespace JWB {	namespace details { namespace graphSearsFunctions
Как sears переводится? Не знаю такого слова, а переводчик что-то странное выдает, возможно ты опечатался

2017-04-13 15:13 UTC, Parean commented on application/inc/inheritanceFactorVisitor.hpp
> +/// @brief Contains result to Method Inheritance Factor (result would be relation of these two).
Лучше ratio вместо relation

2017-04-13 15:13 UTC, Parean commented on application/inc/inheritanceFactorVisitor.hpp
> +	ReturnVisitorStatus<InheritanceFactorVisitor>& result;
Это не замечание, а вопрос:
Я такое впервые вижу, знаю что амперсент используется чтобы по ссылке передавать, а тут это что? Почему не указатель?

2017-04-13 15:13 UTC, Parean commented on application/inc/inheritanceFactorVisitor.hpp
> +	InheritanceFactorVisitor(std::unordered_set<Node const*>& filter, ReturnVisitorStatus<InheritanceFactorVisitor>& result);
У тебя здесь используется unordered_set, но в хедерах его нет, это разве не дурной тон? Все компилируется, потому что оно подключено в другом файле, но мне казалось нужно инклудить все нужные библиотеки везде, разве не для этого pragma once существует?

2017-04-13 15:13 UTC, Parean commented on application/inc/inheritanceTree.hpp
> +	std::vector<std::shared_ptr<Node>> nodes;
const?
Я везде дальше в подобных местах буду это писать, если в этом нет необходимости, то просто грохни потом все эти комменты, чтобы они не мешали, когда будешь править код
Так проще чем приставать в каждом конкретном случае к тебе в slack

2017-04-13 15:13 UTC, Parean commented on application/inc/inheritanceTreeConstructorListener.hpp
> +	/// Enters InterfaceDeclarationContext Node in the tree and creates new mask for future InterfaceDesription.
> Enters InterfaceDeclarationContext Node in the tree 


Эта часть лишняя, внизу то же самое

2017-04-13 15:13 UTC, Parean commented on application/inc/interfaceDescription.hpp
> -#include <memory>
Из-за того, что ты убрал memory, твой код теперь не компилируется

2017-04-13 15:13 UTC, Parean commented on application/inc/interfaceDescription.hpp
> +public:
У нас по стайлгайду у Тимофея вроде было, что после фигурной скобки на следующей строке отступ
Мне как бы не принципиально, но по-моему с отступом красивее выглядит
Весь мой код к тому же с ними, лучше бы все писать одинаково
Но если тебе впадлу править будет, то забей

2017-04-13 15:13 UTC, Parean commented on application/inc/interfaceDescription.hpp
> +	InterfaceDescription(std::string interfaceName);
const?

2017-04-13 15:13 UTC, Parean commented on application/inc/interfaceDescription.hpp
> +	std::vector<std::shared_ptr<MethodDescription>> methods;
const MethodDescription

2017-04-13 15:13 UTC, Parean commented on application/inc/methodDescription.hpp
> +	std::vector<std::string> paramTypes;
const string?

2017-04-13 15:13 UTC, Parean commented on application/inc/methodDescription.hpp
> +	void addParam(std::string paramType);
const string?

2017-04-13 15:13 UTC, Parean commented on application/inc/node.hpp
> +	/// Takes string as a parameter and constuct shared_ptr of a Interface of this name.
String?

2017-04-13 15:13 UTC, Parean commented on application/inc/node.hpp
> +	/// Add inheritor to the contained interface.
Лишний комментарий

2017-04-13 15:13 UTC, Parean commented on application/inc/node.hpp
> +	void addParent(Node* newParent);
И этот тоже

2017-04-13 15:13 UTC, Parean commented on application/inc/node.hpp
> +	/// Returns pointer to interface.
Тоже

2017-04-13 15:13 UTC, Parean commented on application/inc/node.hpp
> +	std::shared_ptr<InterfaceDescription> interfaceDescription;
const?

2017-04-13 15:13 UTC, Parean commented on application/inc/node.hpp
> +	std::vector<Node*> inheritors;
const?

2017-04-13 15:13 UTC, Parean commented on application/inc/node.hpp
> +	std::vector<Node*> parents;
const?

2017-04-13 15:13 UTC, Parean commented on application/inc/treeMetricsCalculator.hpp
> +	double methodInheritanceHidingFactor() const;
Я всем метрикам давал имена начинающиеся с get
Хз имеет ли смысл все в одном стиле делать или нет, сам смотри

2017-04-13 15:13 UTC, Parean commented on application/inc/treePrinterVisitor.hpp
> +class TreePrinterVisitor : public Visitor
Исходя из названия очевидно что он делает, но не очевидно в каком формате
Corresponding message ниже ни о чем не говорит
Напиши комментарий

2017-04-13 15:13 UTC, Parean commented on application/inc/visitor.hpp
> +	virtual void visit(ClassDescription const*) = 0;
Он разве обязан делать пометки? Лучше написать что-нибудь в духе, обрабатывает вершину

2017-04-13 15:13 UTC, Parean commented on application/runSrc/main.cpp
> +  cout << treeMetricsCalculator.widthOfInheritanceTree() << endl;
Добавь сюда так же как я в последней ветке нормальный вывод к гетерам
+печать дерева, пусть оно будет тут, строчку можно всегда закомментировать если что

2017-04-13 15:13 UTC, Parean commented on application/scripts/buildTreeMetrics.sh
> +./JWB ../testExamples/Test.java
Ты добавил новые файлы только из-за последней строчки что ли?
Или ты просто решил переименовать их, но не закоммитил удаление старых? У меня в папке шесть скриптов вместо трех

2017-04-13 15:13 UTC, Parean commented on application/src/classDescription.cpp
> +ClassDescription::ClassDescription(std::string className) :
Зачем std если вверху using

2017-04-13 15:13 UTC, Parean commented on application/src/currentlyBuildingTree.cpp
> +	// As object use after building real tree is not valid, continueing use of the object counts as a bag.
Здесь нужны ассерты на входные параметры?

2017-04-13 15:13 UTC, Parean commented on application/src/currentlyBuildingTree.cpp
> +	// Roots are distingwished from the rest and contained aside.
distingwished

2017-04-13 15:13 UTC, Parean commented on application/src/currentlyBuildingTree.cpp
> +	for (auto nodePointer : nodes)
В каких случаях нужно писать auto, а в каких auto const& ?

2017-04-13 15:13 UTC, Parean commented on application/src/graphSearsFunctions.cpp
> +}}}
Ты везде пишешь end of namespace
Не знаю зачем, но если так делать, то  во всех файлах наверное

2017-04-13 15:13 UTC, Parean commented on application/src/inheritanceFactorVisitor.cpp
> +		/// Maximum number of possibly inherited methods. It is decremented when override found.
assert что ClassDescription не пустой?

2017-04-13 15:13 UTC, Parean commented on application/src/inheritanceFactorVisitor.cpp
> +	struct MethodDescriptionHash{
Давай писать { на отдельной строке

2017-04-13 15:13 UTC, Parean commented on application/src/inheritanceFactorVisitor.cpp
> +		{
Нужен ли здесь и внизу асерт на то, что указатель не нулевой?

2017-04-13 15:13 UTC, Parean commented on application/src/inheritanceFactorVisitor.cpp
> +void InheritanceFactorVisitor::visit(ClassDescription const* classDescription)
Это нормально, что ты принимаешь classDescription и ничего с ним не делаешь?

2017-04-13 15:13 UTC, Parean commented on application/src/inheritanceTree.cpp
> +InheritanceTree::InheritanceTree(vector<Node*> roots, vector<shared_ptr<Node>> nodes) :
Нужен ли тут асерт на непустоту?

2017-04-13 15:13 UTC, Parean commented on application/src/inheritanceTreeConstructorListener.cpp
> +	return AccessModifier::PRIVATE;
Почему private? Уменя сначала было protected, теперь я исправил на default, но private это вообще что-то странное

2017-04-13 15:13 UTC, Parean commented on application/src/inheritanceTreeConstructorListener.cpp
> +	assert(ctx->typeType());
assert что метод не пустой

2017-04-13 15:13 UTC, Parean commented on application/src/inheritanceTreeConstructorListener.cpp
> +	auto const memberDeclaration = ctx->memberDeclaration();
Асерты на непустоту

2017-04-13 15:13 UTC, Parean commented on application/src/interfaceDescription.cpp
> -	assert(newMethod);
Почему ты его убрал?

2017-04-13 15:13 UTC, Parean commented on application/src/methodDescription.cpp
> +		// Invalid argument. Considered a bug.
Теперь еще default появился для классов

2017-04-13 15:13 UTC, Parean commented on application/src/methodDescription.cpp
> +	paramTypes.push_back(move(paramType));
Нужна проверка, что строка не пустая?

2017-04-13 15:13 UTC, Parean commented on application/src/methodDescription.cpp
> +	lazyHash = hasher(stringForHash);
На самом деле мне непонятно, зачем ты сменил id на lazyHash, это как если бы ты поменял attributes на vector

2017-04-13 15:13 UTC, Parean commented on application/src/node.cpp
> +{}
Проверка на непустоту?

2017-04-13 15:13 UTC, Parean commented on application/src/node.cpp
> +{}
Выше тоже

2017-04-13 15:13 UTC, Parean commented on application/src/node.cpp
> +	// visitor should be never nullptr. Otherwise it's a bag.
А нода  разве может быть пустой?

2017-04-13 15:13 UTC, Parean commented on application/src/treeMetricsCalculator.cpp
> +class ClassListsVisitor : public Visitor
Наверное если бы тут были листы, можно было бы так оставить, хотя мне кажется всё-таки что к каждому отдельному классу надо комментарий написать, чтобы он кратко говорил о том, зачем класс нужен
Но в данном конкретном случае, так как у тебя не листы, а деревья, когда ты исправишь всё, комментарий точно будет нужен, потому что название будет очень непонятное, не забудь его добавить

2017-04-13 15:13 UTC, Parean commented on application/src/treeMetricsCalculator.cpp
> +	CurrentlyBuildingTree hierarchyTreeTemplate;
Надо проверять что дерево не пустое?

2017-04-13 15:13 UTC, Parean commented on application/src/treeMetricsCalculator.cpp
> +	inheritanceTree(treeConstruction(parseTree)),
И тут тоже

2017-04-13 15:13 UTC, Parean commented on application/src/treePrinterVisitor.cpp
> +	cout << "Class visited!" << endl;
Нужно ли проверять на непустоту?

2017-04-13 15:13 UTC, Parean commented on application/src/treePrinterVisitor.cpp
> +	cout << "Interface visited!" << endl;
И тут тоже

2017-04-13 15:13 UTC, Parean commented on application/src/visitor.cpp
> +{
Здесь и внизу, нужны ли проверки на непустоту?

2017-04-13 15:13 UTC, Parean commented on application/testExamples/Test.java
> +public interface A
Было бы круто, если бы в этом файле был комментарий, который содержал вывод метрик, которые он тестирует
Плюс, дерево тоже было бы неплохо в том, формате, котором ты его выводишь
Плюс, дай ему нормальное имя, исходя из метрик, для которых он нужен

2017-04-13 15:53 UTC, alexander-bzikadze commented on application/inc/classDescription.hpp
> -#include "accessModifier.hpp"
Вроде он уже в interfaceDesription.hpp подгружен.
Можно конечно лишний раз для понятности

2017-04-13 15:53 UTC, alexander-bzikadze commented on application/inc/classDescription.hpp
> +	std::vector<std::string> attributes;
Этот код потом модифицируется заменой на реальные классы для описания аттрибутов

2017-04-13 15:58 UTC, alexander-bzikadze commented on application/src/graphSearsFunctions.cpp
> +}}}
Я стараюсь это писать в .hpp файлах обязательно

2017-04-13 15:59 UTC, alexander-bzikadze commented on application/inc/currentlyBuildingTree.hpp
> +	/// Adds new interface and its parents to masks.
Ну просто заготовка, интерфейс без наследников и родителей. Их потом добавим

2017-04-13 16:00 UTC, alexander-bzikadze commented on application/inc/currentlyBuildingTree.hpp
> +	/// Adds new interface and its parents to masks.
Это чтобы с наследованием от библиотечных не возиться

2017-04-13 16:00 UTC, alexander-bzikadze commented on application/inc/currentlyBuildingTree.hpp
> +	std::vector<std::shared_ptr<Node>> nodes;
Мы здесь вроде еще их менять должны
Это построение дерева, а не хранилище, так что на мой взгляд можно неконст.

2017-04-13 16:00 UTC, Parean commented on application/inc/currentlyBuildingTree.hpp
> +	/// Adds new interface and its parents to masks.
Добавь пояснение в код пожалуйста, потому что мне было непонятно что это

2017-04-13 16:01 UTC, alexander-bzikadze commented on application/inc/graphSearsFunctions.hpp
> +namespace JWB {	namespace details { namespace graphSearsFunctions
Это search...

2017-04-13 16:01 UTC, alexander-bzikadze commented on application/inc/inheritanceFactorVisitor.hpp
> +	InheritanceFactorVisitor(std::unordered_set<Node const*>& filter, ReturnVisitorStatus<InheritanceFactorVisitor>& result);
Согласен, не заметил

2017-04-13 16:02 UTC, alexander-bzikadze commented on application/inc/inheritanceFactorVisitor.hpp
> +	ReturnVisitorStatus<InheritanceFactorVisitor>& result;
Потому что ссылки для того и нужны, чтобы не указатель хранить)
Так мы гарантируем, что резалт не нулптр например.

2017-04-13 16:03 UTC, alexander-bzikadze commented on application/inc/inheritanceTree.hpp
> +	std::vector<std::shared_ptr<Node>> nodes;
Ага, это удобно
Да, здесь наверное надо конст

2017-04-13 16:05 UTC, alexander-bzikadze commented on application/inc/interfaceDescription.hpp
> +public:
Это не касается отступов после неймспейсов. Если я правильно понял, про что ты

2017-04-13 16:06 UTC, alexander-bzikadze commented on application/inc/interfaceDescription.hpp
> +	std::vector<std::shared_ptr<MethodDescription>> methods;
Здесь может и нет, вроде метод еще конструируется после

2017-04-13 16:07 UTC, alexander-bzikadze commented on application/inc/methodDescription.hpp
> +	void addParam(std::string paramType);
А здесь вроде мув внутри

2017-04-13 16:08 UTC, alexander-bzikadze commented on application/inc/node.hpp
> +	std::shared_ptr<InterfaceDescription> interfaceDescription;
Я посмотрю, но вроде иногда запускаются неконст методы, так что неконст

2017-04-13 16:09 UTC, alexander-bzikadze commented on application/inc/treeMetricsCalculator.hpp
> +	double methodInheritanceHidingFactor() const;
Согласен, переделаю

2017-04-13 16:10 UTC, alexander-bzikadze commented on application/inc/visitor.hpp
> +	virtual void visit(ClassDescription const*) = 0;
Если вершину, то тогда не узнает, в кого попал
Вершина хранит интерфейс. Это чтобы определить интерфейс или класс

2017-04-13 16:11 UTC, Parean commented on application/inc/interfaceDescription.hpp
> +public:
Я про отступы внутри классов
Так как в удаленном коде сверху

2017-04-13 16:12 UTC, alexander-bzikadze commented on application/src/currentlyBuildingTree.cpp
> +	for (auto nodePointer : nodes)
auto const& когда у тебя большой объект и ты не хочешь его менять
Здесь указатель, легче скопировать (даже шаред легче скопировать).

2017-04-13 16:13 UTC, alexander-bzikadze commented on application/src/inheritanceFactorVisitor.cpp
> +		/// Maximum number of possibly inherited methods. It is decremented when override found.
Вроде нода гарантирует, что в ней пустых не лежит

2017-04-13 16:13 UTC, alexander-bzikadze commented on application/src/inheritanceFactorVisitor.cpp
> +	struct MethodDescriptionHash{
Это вспомогательные структурки для мапы вроде, но ладно

2017-04-13 16:15 UTC, alexander-bzikadze commented on application/src/inheritanceFactorVisitor.cpp
> +		{
Можно, но опять же гарантия ноды
Если мы положим в мапу пустой метод, то сами идиоты
Пожалуй все же добавлю

2017-04-13 16:15 UTC, alexander-bzikadze commented on application/src/inheritanceFactorVisitor.cpp
> +void InheritanceFactorVisitor::visit(ClassDescription const* classDescription)
Да, интерфейсу же надо соответствовать

2017-04-13 16:15 UTC, alexander-bzikadze commented on application/src/inheritanceFactorVisitor.cpp
> +void InheritanceFactorVisitor::visit(ClassDescription const* classDescription)
В смысле Visitor::visit(ClD const*)

2017-04-13 16:16 UTC, alexander-bzikadze commented on application/src/inheritanceTree.cpp
> +InheritanceTree::InheritanceTree(vector<Node*> roots, vector<shared_ptr<Node>> nodes) :
Пустоту каждого рута? Думаю, это слишком.
Лучше комментарий, что поведение не определено в таком случае.

2017-04-13 16:17 UTC, alexander-bzikadze commented on application/src/inheritanceTreeConstructorListener.cpp
> +	return AccessModifier::PRIVATE;
В плюсах так, потому так и сделал. Переделаю

2017-04-13 16:18 UTC, alexander-bzikadze commented on application/src/methodDescription.cpp
> +	paramTypes.push_back(move(paramType));
Нужен, хорошо что сказал

2017-04-13 16:19 UTC, alexander-bzikadze commented on application/src/methodDescription.cpp
> +	lazyHash = hasher(stringForHash);
Это я твой код скопировал, но у меня в классе уже был lazyHash много где. Легче было здесь поменять

2017-04-13 16:20 UTC, alexander-bzikadze commented on application/src/node.cpp
> +	// visitor should be never nullptr. Otherwise it's a bag.
Непустота ноды гарантируется тем, кто вызывает.
Добавлю проверку навсякий

2017-04-13 16:20 UTC, Parean commented on application/src/inheritanceTree.cpp
> +InheritanceTree::InheritanceTree(vector<Node*> roots, vector<shared_ptr<Node>> nodes) :
Нет, я про векторы

2017-04-13 16:21 UTC, alexander-bzikadze commented on application/src/treeMetricsCalculator.cpp
> +	CurrentlyBuildingTree hierarchyTreeTemplate;
Надо

2017-04-13 16:21 UTC, alexander-bzikadze commented on application/src/treePrinterVisitor.cpp
> +	cout << "Class visited!" << endl;
Нет вообще, тут вроде гарантия. Но добавлю

2017-04-13 16:22 UTC, Parean commented on application/inc/visitor.hpp
> +	virtual void visit(ClassDescription const*) = 0;
Ну, я имел ввиду, что делает пометки это неправильно
Он может ничего не помечать, а делать что-нибудь другое, зависит же от реализации

2017-04-13 16:23 UTC, alexander-bzikadze commented on application/inc/interfaceDescription.hpp
> +public:
У public: и private: и protected: отступы не ставят

2017-04-13 16:23 UTC, alexander-bzikadze commented on application/src/inheritanceTree.cpp
> +InheritanceTree::InheritanceTree(vector<Node*> roots, vector<shared_ptr<Node>> nodes) :
Аа, векторы непустые
ок

2017-04-13 16:25 UTC, Parean commented on application/src/methodDescription.cpp
> +	lazyHash = hasher(stringForHash);
Современные редакторы меняют все автоматически же, сразу во всем проекте
Это надо переделать

2017-04-13 16:31 UTC, Parean commented on application/inc/interfaceDescription.hpp
> +public:
Окей

2017-04-14 07:30 UTC, alexander-bzikadze commented on application/inc/interfaceDescription.hpp
> +	InterfaceDescription(std::string interfaceName);
Мув

2017-04-14 07:53 UTC, alexander-bzikadze commented on application/inc/visitor.hpp
> +	virtual void visit(ClassDescription const*) = 0;
Notes в смысле заметки, то есть у себя заметки по поводу информации в классе. Внутри interfaceDecsr/classDescr нельзя ничего записать, потому что они по конст переданы.

2017-04-27 16:17 UTC, merged