Add cyclomatic complexity
Parean/semester-project pull request #6
Opened 2017-04-01 14:09 UTC by Parean

2017-04-01 21:12 UTC, alexander-bzikadze requested changes
Большая часть замечаний из предыдущих лет.

2017-04-01 21:12 UTC, alexander-bzikadze commented on application/inc/classDescription.hpp
> +		void addAttribute(AccessModifier const &modifier, string const &newAttribute);
Писал в другом пуллреквесте про const&

2017-04-01 21:12 UTC, alexander-bzikadze commented on application/inc/classDescription.hpp
> +		int getNumberOfAttributes() const;
Равно как и про size_t.

2017-04-01 21:12 UTC, alexander-bzikadze commented on application/inc/customListener.hpp
> +			int numberOfStatements = 0;
size_t?

2017-04-01 21:12 UTC, alexander-bzikadze commented on application/src/customListener.cpp
> +	classesForTraversal.pop();
Ассерты

2017-04-01 21:12 UTC, alexander-bzikadze commented on application/src/customListener.cpp
> +		auto const modifier = m->classOrInterfaceModifier()->getText();
Вероятно, тебе здесь копирования не хочется. Не уверен, но я бы попытался auto const& написать.

2017-04-01 21:12 UTC, alexander-bzikadze commented on application/src/customListener.cpp
> +	for (auto const c : classes)
Здесь тоже наверное auto const&

2017-04-12 15:49 UTC, alexander-bzikadze requested changes
Почти все норм, но шаред из интерфейса прям обязательно убрать

2017-04-12 15:49 UTC, alexander-bzikadze commented on application/inc/interfaceDescription.hpp
> +		void addMethod(std::shared_ptr<MethodDescription> &methodPtr);
Это зря изменение - это дело InterfaceDecription, как хранить указатель на метод
Не надо впихивать шаред птр сюда
И шаред птр мальнький, его можно копировать.
Не понятно, зачем неконст ссылка здесь

2017-04-12 15:49 UTC, alexander-bzikadze commented on application/inc/interfaceDescription.hpp
> +		std::vector <std::shared_ptr <const MethodDescription> > methods;
Передается указатель на просто метод, а хранится константный

2017-04-12 15:49 UTC, alexander-bzikadze commented on application/src/classDescription.cpp
> +#include <iostream>
Это вряд ли нужная библиотека

2017-04-12 15:49 UTC, alexander-bzikadze commented on application/inc/classDescription.hpp
> +		void showCyclomaticComplexities() const;
С учетом того, что можно возвращать имя и среднюю сложность, это лишний метод.

2017-04-12 15:49 UTC, alexander-bzikadze commented on application/src/metricsCalculator.cpp
> +void MetricsCalculator::showCyclomaticComplexities() const
Кажется, что это лишнее - лучше отдельный класс принтер для этого дела. В идеале, мы потом просто это добавим в виде внешнего класса, пока оставить можно.

2017-04-12 15:58 UTC, Parean commented on application/src/metricsCalculator.cpp
> +void MetricsCalculator::showCyclomaticComplexities() const
Этот и верхний методы я для отладки использовал
Внутри этого вызывается тот который выше, поэтому он не лишний

2017-04-12 15:59 UTC, alexander-bzikadze commented on application/src/metricsCalculator.cpp
> +void MetricsCalculator::showCyclomaticComplexities() const
Если они для отладки, то они оба лишние

2017-04-12 17:24 UTC, Parean commented on application/inc/interfaceDescription.hpp
> +		std::vector <std::shared_ptr <const MethodDescription> > methods;
Я наверное просто пропустил это, но это же вроде допустимо? Неконстантный просто станет константным и все

2017-04-12 17:24 UTC, Parean commented on application/src/classDescription.cpp
> +#include <iostream>
Почему? Здесь есть cout

2017-04-12 17:24 UTC, Parean commented on application/src/metricsCalculator.cpp
> +void MetricsCalculator::showCyclomaticComplexities() const
Блин, я отправил раньше чем дописал мысль, прости
Да, они были для отладки, точно так же как и методы showNumberOfMethods и showNumberOfAttributes в metricsCalculator
Но я не думаю, что их нужно удалять, потому что ими удобно пользоваться
Метрики выдают просто число, и его сложно проверить на корректность
Можно попробовать как-то внутри metricsCalculator какой-нибудь namespace printer сделать и туда их все свалить например
Отдельный класс должен будет хранить все данные внутри себя чтобы их выводить, мне не кажется что он нам нужен

2017-04-12 17:43 UTC, alexander-bzikadze commented on application/inc/interfaceDescription.hpp
> +		std::vector <std::shared_ptr <const MethodDescription> > methods;
Да, конечно, потому и компилятор не ругается. Это для программиста.

2017-04-12 17:47 UTC, alexander-bzikadze requested changes

2017-04-12 17:47 UTC, alexander-bzikadze commented on application/src/classDescription.cpp
> +void ClassDescription::showCyclomaticComplexities() const
Я считаю, что это надо убрать

2017-04-13 13:27 UTC, alexander-bzikadze approved these changes

2017-04-13 13:28 UTC, merged