Input from many files
Parean/semester-project pull request #8
Opened 2017-04-21 22:07 UTC by Parean

2017-04-22 20:04 UTC, Parean commented
Я не знаю, насколько это нормальный вариант, складывать архив с библиотекой в проект, но там целая большая папка и библиотеку которую мы используем нужно отдельно компилировать используя ее материалы, поэтому я хз как это все вычленять
Может быть можно потом обсудить это с Юрием или Тимофеем, но пока все делается в лоб и максимально просто, с помощью скрипта

2017-04-27 17:06 UTC, alexander-bzikadze requested changes
Красавец, что с бустом разобрался.
Коробочка для векторов - самая важная часть запрашиваемых изменений.
Ну и еще может надо как оформить ввод, но это пока точно неважно.

2017-04-27 17:06 UTC, alexander-bzikadze commented on application/inc/metricsCalculator.hpp
> +		MetricsCalculator(std::vector <antlr4::CommonTokenStream*> &programTokens, std::vector<antlr4::tree::ParseTree*> &trees);
А калькулятору нужен вектор CommonTokenStream?

2017-04-27 17:06 UTC, alexander-bzikadze commented on application/src/main.cpp
> +void createParseTree(
Вероятно, хочется один класс обработчик этого дела, который можно было бы в калькуляторы засовывать. Но как функция в майне - это точно плохо.

2017-04-27 17:06 UTC, alexander-bzikadze commented on application/src/main.cpp
> +	tree::ParseTree *tree = parser->compilationUnit();
Так, я вроде говорил про то, что new не очень здесь и нужны.

2017-04-27 17:06 UTC, alexander-bzikadze commented on application/src/main.cpp
> +	   cout << "You must specify the path to file or project directory" << endl;
std::cerr

2017-04-27 17:06 UTC, alexander-bzikadze commented on application/src/main.cpp
> +	   cout << "You must specify the path to file or project directory" << endl;
Вообще говоря, это не ошибка, потому 1 не надо возвращать. Отсутствие ввода - корректный ввод. 
Так что здесь с cout сообщение и простой возврат. Там где ошибки, надо cerr

2017-04-27 17:06 UTC, alexander-bzikadze commented on application/inc/metricsCalculator.hpp
> +		MetricsCalculator(std::vector <antlr4::CommonTokenStream*> &programTokens, std::vector<antlr4::tree::ParseTree*> &trees);
Был не прав, но последующий комментарий про коробочку для этих векторов в силе.

2017-04-30 19:28 UTC, Parean commented on application/src/main.cpp
> +void createParseTree(
Мне функция тоже не нравится, но я не знаю как это лучше сделать
Но как сделать хорошо я не знаю
Ты хочешь сделать класс treesGenerator, который будет иметь всего одну функцию generateTrees и инициализировать калькуляторы этим классом, а не вектором деревьев?
Но это плохо, потому что тогда вектор деревьев нужно создавать для каждого калькулятора отдельно
Может наоборот сделать класс, который типо отвечает именно за само приложение (В дальнейшем будет инициализироваться какими-то штуками, которые будут говорить, что именно пользователь хочет, а пока просто принимает путь до директории) и уже этот класс внутри себя сделает деревья, создаст калькуляторы и организует весь вывод? Правда в таком случае в мэйне всего пара строк останется, я не знаю хорошо это или плохо

2017-05-01 08:26 UTC, alexander-bzikadze commented on application/src/main.cpp
> +void createParseTree(
Так как всегда - класс, который дает константный доступ к векторам деревьев. Тогда ты кидаешь один объект во все калькуляторы, главное чтобы они не меняли деревья, но насколько я знаю, этого не происходит.

2017-05-01 14:29 UTC, alexander-bzikadze approved these changes

2017-05-07 13:45 UTC, merged