Metrics for clustering
Parean/semester-project pull request #9
Opened 2017-05-03 11:53 UTC by Parean

2017-05-10 08:56 UTC, Parean commented on application/src/classDescription.cpp
> +	// usedClasses.emplace(className, new forward_list<CouplingType>(1, type));
Хотел спросить у тебя, почему вот так не работает?
Выдает ошибку компиляции

2017-05-10 20:54 UTC, alexander-bzikadze requested changes
Очень сложно такой объем проверять, но что делать. Дал какие-то ценные на мой взгляд комментарии. Интересно только нафиг ты шаблонный Out использовал, в реализации дал комментарии.

2017-05-10 20:54 UTC, alexander-bzikadze commented on application/inc/antlrComponentsKeeper.hpp
> +	AntlrComponentsKeeper(std::string const &stringPath);
Надо бы под произвольное количество строк, но в идеале.

2017-05-10 20:54 UTC, alexander-bzikadze commented on application/inc/classDescription.hpp
> +	std::unordered_map<std::string, std::shared_ptr <std::forward_list <CouplingType> >> usedClasses;
А зачем указатель на форвард_лист?

2017-05-10 20:54 UTC, alexander-bzikadze commented on application/inc/classDescription.hpp
> +	std::vector<std::string const*> privateAttributes;
На самом деле, это не хорошо, но предложить могу либо замену на строку с идиомой copy-on-write (в реализации std::string с 11 стандарта запрещена) с гарантией, что исходная строка не изменится, или еще что-то. Здесь только проблемы дизайна, на работу никак не влияет.

2017-05-10 20:54 UTC, alexander-bzikadze commented on application/inc/clusteringMetricsCalculator.hpp
> +class ClusteringMetricsCalculator : public MetricsBaseCalculator
Ты бы предупредил, что надо унаследоваться)

2017-05-10 20:54 UTC, alexander-bzikadze commented on application/inc/clusteringMetricsCalculator.hpp
> +	size_t getNumberOfConnectedComponents(const std::unordered_map <std::string, std::shared_ptr <MethodDescription> > &methods);
Ощущение, что эта функция не нужна для этого класса и по логике статическая. Тогда предлагается её не объявлять здесь, а просто реализовать в .cpp

2017-05-10 20:54 UTC, alexander-bzikadze commented on application/inc/clusteringMetricsCalculator.hpp
> +	const size_t MAX_ALLOWABLE_VALUE_OF_METRIC = 50;
constexpr - это ничего не сделает, но дает пометку компилятору и разработчикам, что результат известен на этапе компиляции.

2017-05-10 20:54 UTC, alexander-bzikadze commented on application/inc/clusteringMetricsCalculator.hpp
> +	double getLackOfCohesionInMethods4(bool isNormalized = true);
Я погляжу дальше, но кажется, что isNormalized можно было вынести в template параметр.

2017-05-10 20:54 UTC, alexander-bzikadze commented on application/inc/clusteringMetricsListener.hpp
> +	std::vector<std::string> split(const std::string &s, char delim);
Out точно хотим по значению принимать?

2017-05-10 20:54 UTC, alexander-bzikadze commented on application/inc/methodDescription.hpp
> +	CalledMethod(size_t numOfCalls, TypeOfCalledMethod typeOfCalledMethod):
Вроде у структуры уже есть такой конструктор с использованием initializer_list
CalledMethod c = {0, typeOfCalledMethod}.

2017-05-10 20:54 UTC, alexander-bzikadze commented on application/inc/methodDescription.hpp
> +		type(typeOfCalledMethod) {}
Енам можно выносить в темлейтный параметр конструктора, если это удобно.

2017-05-10 20:54 UTC, alexander-bzikadze commented on application/inc/methodDescription.hpp
> +	void addCalledMethod(std::string methodName, TypeOfCalledMethod typeOfCalledMethod);
То же самое про шаблонный параметр.

2017-05-10 20:54 UTC, alexander-bzikadze commented on application/inc/metricsBaseCalculator.hpp
> +class MetricsBaseCalculator
От такого я наследоваться не хочу)
Надо бы еще к названию добавить, чтобы обосновать, почему я от него не наследуюсь.

2017-05-10 20:54 UTC, alexander-bzikadze commented on application/src/classDescription.cpp
>  		privateAttributes.push_back(move(&newAttribute));
Мувить указатель неразумно, потому что ты особо ничего не сделал. Примитивные и маленькие объекты можно не мувить.
Мув - это каст к && на самом деле. Тут это бесполезно, легче скопировать.

2017-05-10 20:54 UTC, alexander-bzikadze commented on application/src/classDescription.cpp
> +	// usedClasses.emplace(className, new forward_list<CouplingType>(1, type));
Честно говоря, не знаю, покажи потом ошибку компиляции

2017-05-10 20:54 UTC, alexander-bzikadze commented on application/src/clusteringMetricsCalculator.cpp
> +}
С предыдущим методом отличается только getUsedClasses/getUsingClasses? Тогда следует сделать один метод, который принимает на вход usingClasses/usedClasses, а первое сообщение можно не вносить в них.

2017-05-10 20:54 UTC, alexander-bzikadze commented on application/src/clusteringMetricsCalculator.cpp
> +double ClusteringMetricsCalculator::getAfferentCoupling(bool isNormalized) const
isNormalized очень на темлейтный параметр похож

2017-05-10 20:54 UTC, alexander-bzikadze commented on application/src/clusteringMetricsListener.cpp
> +		*(result++) = item;
Неочевидно, что result это указатель. Следует принимать Out*

2017-05-10 20:54 UTC, alexander-bzikadze commented on application/src/clusteringMetricsListener.cpp
> +	if(typeid(JavaParser::FormalParameterContext) == typeid(*ctx->parent->parent))
http://en.cppreference.com/w/cpp/types/is_same

2017-05-10 20:54 UTC, alexander-bzikadze commented on application/src/clusteringMetricsListener.cpp
> +	if(typeid(JavaParser::FormalParameterContext) == typeid(*ctx->parent->parent))
через decltype()

2017-05-11 17:13 UTC, Parean commented on application/src/classDescription.cpp
>  		privateAttributes.push_back(move(&newAttribute));
Это видимо осталось еще из очень старой ветки, в которой я в первый раз написал это и забыл исправить во всех дальнейших коммитах

2017-05-11 17:13 UTC, Parean commented on application/src/classDescription.cpp
>  		privateAttributes.push_back(move(&newAttribute));
Понимаю, что это бесполезно

2017-05-11 17:13 UTC, Parean commented on application/src/clusteringMetricsCalculator.cpp
> +}
Принмать функцию как параметр?

2017-05-23 10:40 UTC, Parean commented on application/inc/antlrComponentsKeeper.hpp
> +	AntlrComponentsKeeper(std::string const &stringPath);
Можно будет потом добавить, в этой ветке это лишнее

2017-05-23 12:24 UTC, merged